version: '3'
services:
  postgres:
    image: debezium/postgres
    ports:
      - "5432:5432"
    volumes:
      - /root/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: debezium
      POSTGRES_PASSWORD: debezium

  zookeeper:
    image: debezium/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"

  kafka:
    image: debezium/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECT: "zookeeper"


  debezium:
    image: debezium/connect
    ports:
      - "8083:8083"
    depends_on:
      # - postgres # actually, run this on a separate machine
      - kafka
      - zookeeper
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium
      OFFSET_STORAGE_TOPIC: debezium-connect-offsets
      ADVERTISED_HOST_NAME: localhost
      STATUS_STORAGE_TOPIC: debezium-connect-status
      CONNECT_ZOOKEEPER_CONNECT: zookeeper:2181
      BOOTSTRAP_SERVERS: kafka:9092

  consumer:
    # Upload this image or use https://github.com/ActionSprout/rust-kafka-consumer-example
    image: people-consumer
    depends_on:
      - kafka
    environment:
      KAFKA_URL: kafka:9092
      RUST_LOG: info
      TOPIC: debezium.public.people
